### Create a new JSON Blob
POST http://localhost:3030/api/jsonBlob
Content-Type: application/json

{
  "name": "Example",
  "type": "Test",
  "active": true
}

### Get a JSON Blob by ID
# Replace {blobId} with the actual blobId returned from the POST request
GET http://localhost:3030/api/jsonBlob/{blobId}

### Update an existing JSON Blob
# Replace {blobId} with the actual blobId you want to update
PUT http://localhost:3030/api/jsonBlob/{blobId}
Content-Type: application/json

{
  "name": "Updated Example",
  "type": "Updated Test",
  "active": false
}

### Delete a JSON Blob
# Replace {blobId} with the actual blobId you want to delete
DELETE http://localhost:3030/api/jsonBlob/{blobId}

### TESTING MONGODB CONNECTION -- DELETE
GET http://localhost:3030/mongodb

### TESTING CHAT -- DELETE
POST http://localhost:3030/api/test-chat
Content-Type: application/json



### TEST FILE UPLOAD TO S3
# Returns { url: req.file.location, key: req.file.key }
# This url unuseable though, unless we get a signed one
POST http://localhost:3030/api/files/upload
Content-Type: multipart/form-data; boundary=IamSplitter

--IamSplitter
Content-Disposition: form-data; name="image"; filename="69.png"
Content-Type: image/png

< ./cloud.png
--IamSplitter--


### TEST GET SIGNED URL FROM S3
# Returns { url: url } that can be viewed anywere
GET http://localhost:3030/api/files/1745508408311_69.png


### TEST GET CHAT BY CHATID
# /api/chats/:chatId
GET http://localhost:3030/api/chats/68018ab8d1a8efbe05f93f04
Authorization: 67fe7fe1914b5891b9b5f899


### TEST GET ALL CHATS
GET http://localhost:3030/api/chats/
Authorization: 67fe7fe1914b5891b9b5f899


### TEST SEND MESSGE TO AI
# /api/chats/:chatId/messages
POST http://localhost:3030/api/chats/68018ab8d1a8efbe05f93f04/messages
Content-Type: application/json
Authorization: 67fe7fe1914b5891b9b5f899

{
  "text": "Make it up",
  "model": "gemma2-9b-it"
}

### TEST SEND IMAGE MODEL MESSGE TO AI
# /api/chats/:chatId/messages
POST http://localhost:3030/api/chats/68018ab8d1a8efbe05f93f04/messages
Content-Type: application/json
Authorization: 67fe7fe1914b5891b9b5f899

{
  "text": "Help",
  "model": "meta-llama/llama-4-scout-17b-16e-instruct",
  "imageUrl": "https://www.google.com/imgres?q=eiffel%20tower&imgurl=https%3A%2F%2Fmedia.cnn.com%2Fapi%2Fv1%2Fimages%2Fstellar%2Fprod%2F120210044639-eiffel-tower.jpg%3Fq%3Dw_3015%2Ch_2010%2Cx_0%2Cy_0%2Cc_fill&imgrefurl=https%3A%2F%2Fwww.cnn.com%2Ftravel%2Farticle%2Feiffel-tower-guide%2Findex.html&docid=aiUaznG2mJWYyM&tbnid=ds6yj271Fxe8oM&vet=12ahUKEwiGgvvGkvKMAxWQMtAFHcrZNWIQM3oECFYQAA..i&w=3015&h=2010&hcb=2&ved=2ahUKEwiGgvvGkvKMAxWQMtAFHcrZNWIQM3oECFYQAA"
}

### TEST SEND MESSGE TO AI
# /api/chats/:chatId/messages
POST http://localhost:3030/api/chats/68018ab8d1a8efbe05f93f04/messages
Content-Type: application/json
Authorization: 67fe7fe1914b5891b9b5f899

{
  "text": "Can you write it for me",
  "model": "meta-llama/llama-4-scout-17b-16e-instruct"
}


### CREATE NEW CHAT
# /api/chats
POST http://localhost:3030/api/chats
Content-Type: application/json
Authorization: 67fe7fe1914b5891b9b5f899

{
  "message": "hello",
  "model": "gemma2-9b-it",
  "title": "hello"
}


### GET UPLOAD URL
POST http://localhost:3030/api/files/getPostUrl
Content-Type: application/json

{
  "filename": "testfile.jpg",
  "contentType": "image/jpg"
}

### CLIENT!!! SEND STRAIGHT TO S3
PUT https://chat-220.s3.us-east-2.amazonaws.com/1745549402215_testfile.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIA6GBMHAWX4B7ET67O%2F20250425%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20250425T025002Z&X-Amz-Expires=300&X-Amz-Signature=a079b524e30d517090a6b860e0a2c24f8057b4e817d748e8af40b51316698391&X-Amz-SignedHeaders=host&x-amz-checksum-crc32=AAAAAA%3D%3D&x-amz-sdk-checksum-algorithm=CRC32&x-id=PutObject
Content-Type: image/png

{
  ...
}


### TEST GET TEMP URL FOR IMAGE
GET http://localhost:3030/api/files/1745508408311_69.png


### Test TTS
POST http://localhost:3030/api/chats/tts 
Content-Type: application/json

{
  "text": "The image depicts a blue, pixelated illustration of a dolphin. The dolphin is viewed from the side, facing to the right. It has a large dorsal fin on its back and a long, curved tail. The dolphin's body is a solid blue color, with no visible details or shading. The background of the image is white. The overall effect is one of simplicity and boldness, with the bright blue color of the dolphin standing out against the plain white background."
}
