###
//checking email in use
GET http://localhost:3030/api/auth/check-email?email=asdasd

###
//signing up a user
POST http://localhost:3030/api/auth/signup
Content-Type: application/json

{
  "email":"blahblah@gmail.com",
  "password":"asdasd123"
}

###
//logging a user in
POST http://localhost:3030/api/auth/login
Content-Type: application/json

{
  "email":"blahblah@gmail.com",
  "password":"asdasd123"
}